version: '3.8'

services:
  # Original setup without Elasticsearch
  backend:
    build:
      context: ./elastic-search-express
      dockerfile: Dockerfile
    container_name: elastic-search-express
    ports:
      - '3001:3001'
    volumes:
      - ./elastic-search-express:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./elastic-search-react
      dockerfile: Dockerfile
    container_name: elastic-search-react
    ports:
      - '5173:5173'
    volumes:
      - ./elastic-search-react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  db:
    image: 'nouchka/sqlite3'
    container_name: sqlite-db
    volumes:
      - ./elastic-search-express/src/db:/db
    command: tail -f /dev/null  # Keep the container running

  # New setup with Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  backend_es:
    build:
      context: ./elastic-search-express
      dockerfile: Dockerfile
    container_name: elastic-search-express-es
    ports:
      - '3002:3001'
    volumes:
      - ./elastic-search-express:/app
      - /app/node_modules
    depends_on:
      - db
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  frontend_es:
    build:
      context: ./elastic-search-react
      dockerfile: Dockerfile
    container_name: elastic-search-react-es
    ports:
      - '5174:5173'
    volumes:
      - ./elastic-search-react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:3002  # Point to the Elasticsearch-enabled backend
    depends_on:
      - backend_es

volumes:
  esdata:
    driver: local