version: '3.8'

services:
  backend:
    build:
      context: ./elastic-search-express
      dockerfile: Dockerfile
    container_name: elastic-search-express
    ports:
      - '3001:3001'
    volumes:
      - ./elastic-search-express:/app
    depends_on:
      - db
      - elasticsearch

  frontend:
    build:
      context: ./elastic-search-react
      dockerfile: Dockerfile
    container_name: elastic-search-react
    ports:
      - '5173:5173'
    volumes:
      - ./elastic-search-react:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  db:
    image: 'nouchka/sqlite3'
    container_name: sqlite-db
    volumes:
      - ./elastic-search-express/src/db:/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
