version: '3.8'

services:
  backend:
    build:
      context: ./elastic-search-express
      dockerfile: Dockerfile
    container_name: elastic-search-express
    ports:
      - '3001:3001'
    volumes:
      - ./elastic-search-express:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./elastic-search-react
      dockerfile: Dockerfile
    container_name: elastic-search-react
    ports:
      - '5173:5173'
    volumes:
      - ./elastic-search-react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  db:
    image: 'nouchka/sqlite3'
    container_name: sqlite-db
    volumes:
      - ./elastic-search-express/src/db:/db
    command: tail -f /dev/null  # Keep the container running